name: AssassinMinigame
main: tenny1028.assassin.AssassinMinigame
version: 2.0

commands:
  assassin:
    description: Controls the Assassin Minigame
    usage: /assassin <join|leave|start|leaderboards|spawn>